#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_TEST)		+= test_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_TEST)		+= test_lock_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_TEST)		+= test_lock2_hwspinlock.o
