obj-$(CONFIG_RPMSG)	+= rpmsg_core.o
rpmsg_core-y		:= rpmsg_bus.o rpmsg_virtio.o

obj-$(CONFIG_RPMSG_CLIENT_SAMPLE) += rpmsg_client_sample.o
obj-$(CONFIG_RPMSG_SERVER_SAMPLE) += rpmsg_server_sample.o
obj-$(CONFIG_RPMSG_OMX) += rpmsg_omx.o
